server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Omkar66527
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config :
    import : configserver:${CONFIG_SERVER_URL:http://localhost:9296}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-34099492.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            clientId: 
            clientSecret: 
        provider:
          okta:
            issuerUri: https://dev-34099492.okta.com/oauth2/default

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

resilience4j:
  circuitbreaker:
    instances:
      external:
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

#okta:
#  oauth2:
#    issuer: https://dev-34099492.okta.com/oauth2/default
#    audience: api://default


